% Define knitr options
% !Rnw weave = knitr
% Set global chunk options
<<knitr_setup,include=FALSE,cache=FALSE>>=
library(knitr)
opts_chunk$set(prompt=TRUE, comment=NA, highlight=FALSE, message=FALSE, warning=FALSE, size='scriptsize', fig.width=4, fig.height=4)
options(width=60, dev='pdf')
thm <- knit_theme$get("acid")
knit_theme$set(thm)
@


% Define document options
\documentclass[10pt]{beamer}
\mode<presentation>
\usetheme{AnnArbor}
% \usecolortheme{whale}
% Uncover everything in a step-wise fashion
% \beamerdefaultoverlayspecification{<+->}
% amsmath package for math symbols
% \usepackage{amsmath}
\usepackage[latin1]{inputenc}
\usepackage{hyperref}
\usepackage{fancybox}
\usepackage{url}
\usepackage[backend=bibtex,style=alphabetic]{biblatex} % bibstyle=numeric
% \bibliographystyle{amsalpha} % doesn't work
\addbibresource{FRE6811_bib.bib}
% \addbibresource[location=remote]{http://www.citeulike.org/user/jerzyp}
\renewcommand\bibfont{\footnotesize}
\renewcommand{\pgfuseimage}[1]{\scalebox{0.75}{\includegraphics{#1}}} % scale bib icons
\setbeamertemplate{bibliography item}[text] % set bib icons
% \setbeamertemplate{bibliography item}{} % remove bib icons

% \usepackage{enumerate}
% \let\emph\textbf
% \let\alert\textbf
% Define colors for hyperlinks
\definecolor{links}{HTML}{2A1B81}
\hypersetup{colorlinks=true,linkcolor=,urlcolor=links}
% Make url text footnotesize
\renewcommand\UrlFont{\footnotesize}
% Make institute text italic and small
\setbeamerfont{institute}{size=\small,shape=\itshape,bg=red,fg=red}
\setbeamerfont{date}{size=\small}
\setbeamerfont{block title}{size=\normalsize} % shape=\itshape
\setbeamerfont{block body}{size=\footnotesize}


% Title page setup
\title[FRE6811 Lecture \#1]{FRE6811 Financial Software Laboratory}
\subtitle{Lecture \#1, Spring 2014}
% \subject{Getting Started With R}
\institute[NYU Polytechnic]{NYU Polytechnic School of Engineering}
\titlegraphic{\includegraphics[scale=0.8]{engineering_long_color}}
\author{Jerzy Pawlowski}
% \email{jp3900@poly.edu}
\date{January 27, 2014}
% \date{\today}
% \pgfdeclareimage[height=0.5cm]{university-logo}{engineering_long_white}
% \logo{\pgfuseimage{engineering_long_white}}


%%%%%%%%%%%%%%%
\begin{document}


%%%%%%%%%%%%%%%
\maketitle


%%%%%%%%%%%%%%%
\section{$R$ Packages}


%%%%%%%%%%%%%%%
\subsection{\secname}
\begin{frame}[fragile,t]{\subsecname}

\begin{block}{Types of \subsecname}
  $R$ can run libraries of functions called packages,
  \vskip1ex
  $R$ packages can can also  contain data,
  \vskip1ex
  Most packages need to be \emph{loaded} into $R$ before they can be used,
  \vskip1ex
  $R$ includes a number of \emph{base} packages that are already installed and loaded,
  \vskip1ex
  There's also a special package called the \verb|base| package, which is responsible for all the basic $R$ functionality,
  \vskip1ex
  \verb|datasets| is a \emph{base} package containing various datasets, for example \verb|EuStockMarkets|,
  \vskip1ex
\end{block}

\end{frame}


%%%%%%%%%%%%%%%
\subsection{Loading Packages}
\begin{frame}[fragile,t]{\subsecname}

\begin{block}{Loading Packages}
$R$ can run external libraries of functions called packages,\\
Most packages need to be loaded before they can be used,
  \begin{columns}[T]
    \column{0.5\textwidth}
      There are two ways of loading package \verb|MASS|
    \column{0.5\textwidth}
      \vspace{-1em}
      <<tidy=FALSE,eval=FALSE>>=
library("MASS") or require("MASS")
      @
  \end{columns}
\end{block}
%\vskip1ex
\pause

\begin{block}{Difference between library() and require()}
\verb|library()| halts execution if the package can't be loaded,\\
\verb|require()| returns a logical value, TRUE if the package is loaded, FALSE if it isn't.\\
\end{block}
\pause

\begin{block}{\color{red}{Rule of Thumb}}
Use \verb|library()| in script files that might be sourced,\\
Use \verb|require()| inside other functions.\\
\end{block}
\pause

\begin{block}{Installing Packages}
Some packages like \verb|MASS| are installed with base $R$ (but not loaded),\\
But most packages need to be $installed$ before they can be loaded,\\
\end{block}

\end{frame}


%%%%%%%%%%%%%%%
\subsection{Installing Packages}
\begin{frame}[fragile,t]{\subsecname}

\begin{block}{Installing Packages from $CRAN$}
Most of the widely used packages are available on $CRAN$,\\
For example package \verb|AER|:\\
\hskip1em\url{http://cran.us.r-project.org/web/packages/AER/}\\
  \begin{columns}[T]
    \column{0.5\textwidth}
      Install and load package \verb|AER| in $R$ Session:
    \column{0.5\textwidth}
      \vspace{-1em}
      <<tidy=FALSE,eval=FALSE>>=
install.packages("AER")
library("AER")
      @
  \end{columns}
\end{block}
\pause

\begin{block}{Installing packages in $RStudio$}
Go to \alert{Tools} and then \alert{Install packages}\\
Then enter package name, for example \verb|AER|
\end{block}
\pause

\begin{block}{Packages on $R-Forge$}
Many other packages are available on $R-Forge$:\\
\hskip1em\url{https://r-forge.r-project.org/}\\
For example packages which are part of the $ReturnAnalytics$ project,\\
\hskip1em\url{https://r-forge.r-project.org/projects/returnanalytics/}\\
\hskip1em\url{https://r-forge.r-project.org/R/?group_id=579}\\
  \begin{columns}[T]
    \column{0.3\textwidth}
      Install package $PerformanceAnalytics$
    \column{0.7\textwidth}
      \vspace{-1em}
      <<tidy=FALSE,eval=FALSE>>=
install.packages("PerformanceAnalytics", 
                 repos="http://R-Forge.R-project.org")
      @
  \end{columns}
\end{block}

\end{frame}


%%%%%%%%%%%%%%%
\subsection{$CRAN$ Package Views}
\begin{frame}[fragile,t]{\subsecname}

\begin{columns}[T]
  \column{0.4\textwidth}
    \begin{block}{}
      $CRAN$ view for package \verb|AER|:\\
      \hskip1em\url{http://cran.us.r-project.org/web/packages/AER/}\\
    \end{block}
    \begin{block}{}
      Note:
      \begin{itemize}
        \item Authors,
        \item Version number,
        \item Reference manual,
        \item Vignettes,
        \item Dependencies on other packages.
      \end{itemize}
    \end{block}
  \column{0.6\textwidth}
    \vspace{-1em}
    \includegraphics[height=1.0\textwidth]{CRAN_Package.png}
\end{columns}

\end{frame}


%%%%%%%%%%%%%%%
\subsection{$CRAN$ Task Views}
\begin{frame}[fragile,t]{\subsecname}

\begin{columns}[T]
  \column{0.4\textwidth}
    \begin{block}{}
      $CRAN$ Finance Task View\\
      \hskip1em\url{http://cran.us.r-project.org/}\\
    \end{block}
    \begin{block}{}
      Note:
      \begin{itemize}
        \item Maintainer,
        \item Topics,
        \item List of packages.
      \end{itemize}
    \end{block}
  \column{0.6\textwidth}
    \vspace{-1em}
    \includegraphics[height=1.0\textwidth]{CRAN_Views.png}
\end{columns}

\end{frame}


%%%%%%%%%%%%%%%
\subsection{Exploring Packages}
\begin{frame}[fragile,t]{\subsecname}

\begin{block}{}
  \begin{columns}[T]
    \column{0.3\textwidth}
      The package \verb|Ecdat| contains data sets for econometric analysis,
      \vskip1ex
      The data frame \verb|Garch| contains daily currency prices,
    \column{0.7\textwidth}
      \vspace{-1em}
      <<tidy=FALSE,eval=FALSE>>=
packageDescription("Ecdat")  # get short description
help(package="Ecdat")  # get full documentation for package "Ecdat"
ls("package:Ecdat")  # list all objects in package "Ecdat"
data(package="Ecdat")  # show all datasets in package "Ecdat"
detach("package:Ecdat")  # remove package from list
      @

      <<>>=
library("Ecdat")  # data sets for econometric analysis
class(Garch)
dim(Garch)  # daily currency prices
head(Garch[, -2])  # col 'dm' is Deutsch Mark
      @
  \end{columns}
\end{block}

\end{frame}


%%%%%%%%%%%%%%%
\subsection{References}
\begin{frame}[fragile,t]{\subsecname}

There will be no required textbook, but a recommended textbook is:\\
{\small{\fullcite{rupperttexbook}}}\\

$RStudio$:\\
{\small{\fullcite{website:rstudioide}}}\\

An R resource:\\
{\small{\fullcite{website:cran}}}\\

Google Style Guide for R:\\
{\small{\fullcite{website:googlestyler}}}\\

\end{frame}


%%%%%%%%%%%%%%%
\subsection{Bibliography}
\begin{frame}[fragile,t,allowframebreaks]{\subsecname}

\nocite{*} % print all bib file entries
{\tiny{\printbibliography}}

% doesn't work as expected - prints only books
% \printbibliography[type=book,title={Books}] % print books
% \printbibliography[type=online,title={Websites}] % print Websites

\end{frame}


%%%%%%%%%%%%%%%
\subsection{Creative Commons Attribution-ShareAlike License}
\begin{frame}[t]{\subsecname}
\small{
\begin{columns}[T]
  \column[T]{0.5\textwidth}
    You are free to:
    \vspace{0.6em}
    \begin{itemize}[<+->]
      \item Share - copy and redistribute the material in any medium or format.
      \item Adapt - remix, transform, and build upon the material for any purpose, even commercially.
    \end{itemize}
    \pause
  \column[T]{0.5\textwidth}
    Under the following terms:
    \begin{itemize}[<+->]
      \item Attribution - You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
      \item ShareAlike - If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
    \end{itemize}
\end{columns}
}
\end{frame}


\end{document}

